version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
       twilight-dependencies:
          patterns:
            - "twilight-*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"